# Generated by Django 4.2.23 on 2025-07-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kuti',
            old_name='is_avaiable',
            new_name='is_available',
        ),
    ]
