# Generated by Django 4.2.23 on 2025-07-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_registration_phone_number_and_more'),
        ('kuti', '0002_rename_is_avaiable_kuti_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuti',
            name='current_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.registration'),
        ),
    ]
