# Generated by Django 4.2.23 on 2025-06-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0001_initial'),
        ('kuti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KutiAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('kuti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kuti.kuti')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='registration.registration')),
            ],
            options={
                'verbose_name': 'Kuti Assignment',
                'verbose_name_plural': 'Kuti Assignments',
                'unique_together': {('registration', 'kuti')},
            },
        ),
    ]
