# Generated by Django 4.2.23 on 2025-07-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutiassignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kutiassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kutiassignment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
