# Generated by Django 4.2.23 on 2025-07-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GuestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('short_content', models.CharField(blank=True, max_length=300, verbose_name='Nội dung rút gọn')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm trả lời')),
                ('status', models.CharField(choices=[('answered', 'Đã trả lời'), ('pending', 'Chưa trả lời')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('high', 'Cao'), ('medium', 'Vừa'), ('low', 'Thấp')], default='medium', max_length=10, verbose_name='Độ ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest_question.questiongroup', verbose_name='Nhóm câu hỏi')),
                ('tags', models.ManyToManyField(blank=True, to='guest_question.questiontag', verbose_name='Tag')),
            ],
        ),
    ]
