# Generated by Django 4.2.23 on 2025-07-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0002_alter_guestquestion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestquestion',
            name='answer',
            field=models.TextField(default=1, verbose_name='Nội dung câu trả lời'),
            preserve_default=False,
        ),
    ]
