# Generated by Django 4.2.23 on 2025-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0003_guestquestion_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestquestion',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung câu trả lời'),
        ),
    ]
