# Generated by Django 4.2.23 on 2025-07-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0004_alter_guestquestion_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestquestion',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contact SĐT hoặc email hoặc link fb'),
        ),
    ]
