# Generated by Django 4.2.23 on 2025-07-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0006_alter_guestquestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestquestion',
            name='slideshow',
            field=models.BooleanField(default=False, verbose_name='Hiển thị slideshow'),
        ),
    ]
