# Generated by Django 4.2.23 on 2025-07-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0007_guestquestion_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestquestion',
            name='group',
            field=models.CharField(blank=True, null=True, verbose_name='Nhóm câu hỏi'),
        ),
        migrations.RemoveField(
            model_name='guestquestion',
            name='tags',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
        migrations.AddField(
            model_name='guestquestion',
            name='tags',
            field=models.CharField(blank=True, null=True, verbose_name='Tags'),
        ),
    ]
