# Generated by Django 4.2.23 on 2025-07-19 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0008_alter_guestquestion_group_remove_guestquestion_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='guestquestion',
            name='tags',
        ),
        migrations.AlterField(
            model_name='guestquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest_question.questiongroup', verbose_name='Nhóm câu hỏi'),
        ),
        migrations.AddField(
            model_name='guestquestion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='guest_question.questiontag', verbose_name='Tag'),
        ),
    ]
