# Generated by Django 4.2.23 on 2025-07-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0009_questiongroup_questiontag_remove_guestquestion_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestquestion',
            name='group',
            field=models.CharField(blank=True, null=True, verbose_name='group'),
        ),
        migrations.RemoveField(
            model_name='guestquestion',
            name='tags',
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
        migrations.DeleteModel(
            name='QuestionTag',
        ),
        migrations.AddField(
            model_name='guestquestion',
            name='tags',
            field=models.CharField(blank=True, null=True, verbose_name='tags'),
        ),
    ]
