# Generated by Django 4.2.23 on 2025-07-22 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guest_question', '0010_alter_guestquestion_group_remove_guestquestion_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guestquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Câu hỏi khách', 'verbose_name_plural': 'Câu hỏi khách'},
        ),
        migrations.AddField(
            model_name='guestquestion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='guestquestion',
            name='is_faq',
            field=models.BooleanField(default=False, verbose_name='Hiển thị trên trang câu hỏi thường gặp'),
        ),
        migrations.AddField(
            model_name='guestquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AddField(
            model_name='guestquestion',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_questions', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='guestquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='guestquestion',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhóm câu hỏi'),
        ),
        migrations.AlterField(
            model_name='guestquestion',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tags'),
        ),
    ]
