# Generated by Django 4.2.23 on 2025-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_question', '0011_alter_guestquestion_options_guestquestion_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestquestion',
            name='edited_content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung câu hỏi đã hiên tập'),
        ),
    ]
