# Generated by Django 4.2.23 on 2025-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('checked_in', 'checked_in'), ('checked_out', 'checked_out'), ('expired', 'expired')], default='pending', max_length=20),
        ),
    ]
