# Generated by Django 4.2.23 on 2025-07-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_registration_reject_reason_alter_registration_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='registration',
            new_name='phone_number',
            old_name='idx_phone_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='kuti_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
