# Generated by Django 4.2.23 on 2025-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_idx_phone_number_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='registration',
            name='phone_number',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='phone_number',
            new_name='username',
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['username'], name='username'),
        ),
    ]
