# Generated by Django 4.2.23 on 2025-07-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_registration_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cccd',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=12),
        ),
    ]
